### ISSUE TITLE
Can't locate object method "new" via package "Mojo::JSON" at .../Heroku.pm line 88, <STDIN> line 3.

### ISSUE THREAD

**Issue by Revlin** [tempire/mojolicious-command-deploy-heroku#9]
```$ ./my-app.pl deploy heroku --create```
...  outputs:
```Uploading SSH public key /home/.../.ssh/id_rsa.pub```
```Can't locate object method "new" via package "Mojo::JSON" at /home/.../perl5/lib/perl5/Net/Heroku.pm line 88, <STDIN> line 3.```

Where should I begin trying to resolve this?

Thanks

**Comment by tempire** [comment]
It’s assuming an older version of mojolicious where Mojo::JSON is an object. It’s now a functional interface that uses encode_json, or json_encode (I always get them mixed up).

If you make the change and make a pull request on github, I’ll merge it in and release a new module version.

**Comment by tempire** [comment]
I'm about to deploy a version, if you make the PR in the next several hours, it will get out quickly.

**Comment by Revlin** [comment]
K, I just forked the repo and I'm having a look

**Comment by Revlin** [comment]
After updating UserAgent.pm to use `encode_json` I tried running the tests with this result:

```
t/heroku.t .. 1/? Can't call method "is_abs" without a package or object reference at /home/.../perl5/lib/perl5/Mojo/UserAgent.pm line 313.
    # Child (releases) exited without calling finalize()

#   Failed test 'releases'
#   at /home/.../perl5/lib/perl5/Test/Builder.pm line 279.
# Tests were run but no plan was declared and done_testing() was not seen.
# Looks like your test exited with 255 just after 9.
t/heroku.t .. Dubious, test returned 255 (wstat 65280, 0xff00)
Failed 1/9 subtests 
    (less 7 skipped subtests: 1 okay)
```

So... I went ahead and uncommented the line to skip these test ( `plan skip_all => 'because' unless TEST;`) ... and installed the updated source, but that test result seems to be significant. Now running the create command gives me:

```
Can't call method "is_abs" without a package or object reference at /home/.../perl5/lib/perl5/Mojo/UserAgent.pm line 313.
```

**Comment by tempire** [comment]
is_abs is a method from Mojo::URL, if that helps.

**Comment by Revlin** [comment]
Well, I'm still trying to figure this out, but the error seems to be connected to the way Net::Heroku::UserAgent extends Mojo::UserAgent

**Comment by Revlin** [comment]
Looks like only someone with administrative access to the 'cpantests@empireenterprises.com' heroku account can make use of these tests because if I `say $res->body` in the `create` function I see:

```
{"id":"invalid_params","error":"You've reached the limit of 5 apps for unverified accounts.\nDelete some apps or add a credit card to verify your account."}
```

**Comment by tempire** [comment]
It’s an arbitrary account. You can use any free heroku account to test.

**Comment by dancingfrog** [comment]
Can't remember why this was closed but I still see this error on deploy, with Mojolicious 7.09:

```
Can't locate object method "new" via package "Mojo::JSON" at /.../5.20.2/Net/Heroku.pm line 88.
```

**Comment by dancingfrog** [comment]
Ah, now I remember. The problem is with [net-heroku](https://github.com/tempire/net-heroku)
